VERSION: latest
ENV_VARS:
  GF_LOG_LEVEL: "DEBUG"
  GF_LOG_MODE: "console"
  GF_SERVER_HTTP_PORT: "${NOMAD_PORT_http}"
  GF_PATHS_PROVISIONING: "/local/grafana/provisioning"
  GF_PATHS_CONFIG: "/local/grafana/grafana.ini"
GRAFANAINI: ""
ARTIFACTS:
  - source: "https://grafana.com/api/dashboards/1860/revisions/26/download"
    destination: "local/grafana/provisioning/dashboards/linux/linux-node-exporter.json"
    mode: "file"
    options: null

DASHBOARDS: |
 apiVersion: 1
 providers:
   - name: dashboards
     type: file
     updateIntervalSeconds: 30
     options:
       foldersFromFilesStructure: true
       path: /local/grafana/provisioning/dashboards

DATASOURCES: |
 apiVersion: 1
 datasources:
   - name: Prometheus
     type: prometheus
     access: proxy
     url: http://prometheus.service.{{ env "NOMAD_DC" }}.consul:9090
     jsonData:
       exemplarTraceIdDestinations:
         - name: traceID
           datasourceUid: tempo
   - name: Tempo
     type: tempo
     access: proxy
     url: http://tempo.service.{{ env "NOMAD_DC" }}.consul:3200
     uid: tempo
   - name: Loki
     type: loki
     access: proxy
     url: http://loki.service.{{ env "NOMAD_DC" }}.consul:3100
     jsonData:
       derivedFields:
         - datasourceUid: tempo
           matcherRegex: (?:traceID|trace_id)=(\w+)
           name: TraceID
           url: $$${__value.raw}

PLUGINS: ""
